language: node_js
node_js:
  - "node"
before_install:
  - npm i -g makeshift && makeshift -s @erikeuserr -r https://registry.npmjs.org
deploy:
  provider: npm
  email: erikeuserr@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master